version: "3"
services:
  postgresdb:
    image: postgres
    restart: always
    container_name: copang-dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=yapp
      - POSTGRES_PASSWORD=yapp
    volumes:
      - postgresdb:/var/lib/postgres

  redisdb:
    image: redis
    restart: always
    ports:
      - 6379:6379
    container_name: yapp-redis
    volumes:
      - redisdb:/var/lib/redis
