FROM eclipse-temurin:17-jdk-alpine
EXPOSE 8080
ARG JAR_FILE=/build/libs/copang-order-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} copang-dev.jar
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=dev","/copang-dev.jar"]
