server:
  port: 8080

spring:
  config:
    import: application-db.yml

---
################################ local ################################
spring:
  config:
    activate:
      on-profile: local

copang:
  servers:
    auth: http://localhost:8080
    product: http://localhost:8080
---
################################ test ################################
spring:
  config:
    activate:
      on-profile: test

copang:
  servers:
    auth: dummy
    product: dummy
---
################################ live ################################
spring:
  config:
    activate:
      on-profile: live

copang:
  servers:
    auth: http://localhost:3000
    product: http://localhost:8080
