name: ktlint

on:
  pull_request:

jobs:
  ktlint:
    runs-on: [ Linux ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint with Kotlinter
        run: ./gradlew ktlintCheck
