name: ktlint

on:
  workflow_run:
    workflows:
      - First Workflow
    types:
      - completed

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint with Kotlinter
        run: ./gradlew ktlintCheck
